// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jbtK4JeXwnEpviHioF7Qj-ii_FoNLGI',
    appId: '1:442613986021:web:1cd185e08b9658f051da0c',
    messagingSenderId: '442613986021',
    projectId: 'aimchat-15b34',
    authDomain: 'aimchat-15b34.firebaseapp.com',
    storageBucket: 'aimchat-15b34.firebasestorage.app',
    measurementId: 'G-CS3HZG9DD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduFS6n2VZICaZorxlra5-9uxmaTTCQkE',
    appId: '1:442613986021:android:5acd6044303ec21651da0c',
    messagingSenderId: '442613986021',
    projectId: 'aimchat-15b34',
    storageBucket: 'aimchat-15b34.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhOhgU8InxlAMXVTOdXRLZD3YyBg2zeQw',
    appId: '1:442613986021:ios:2e645d88a76a7a0d51da0c',
    messagingSenderId: '442613986021',
    projectId: 'aimchat-15b34',
    storageBucket: 'aimchat-15b34.firebasestorage.app',
    iosBundleId: 'com.aiworkspace.app',
  );
}
