import 'dart:async';
import 'dart:ui' show PlatformDispatcher;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'core/errors/app_exception.dart';
import 'core/routing/app_router.dart';
import 'firebase_options.dart';
import 'providers/ai_provider_config_provider.dart';
import 'providers/auth_provider.dart';
import 'providers/chat_provider.dart';
import 'providers/conversation_provider.dart';
import 'providers/theme_provider.dart';
import 'services/auth_service.dart';
import 'services/chat_service.dart';
import 'services/conversation_service.dart';
import 'services/openai_compatible_chat_service.dart';
import 'services/provider_config_service.dart';
import 'services/secure_storage_service.dart';
import 'theme/app_theme.dart';

Future<void> main() async {
  await runZonedGuarded<Future<void>>(
    () async {
      WidgetsFlutterBinding.ensureInitialized();

      await SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight,
      ]);

      // Initialize Firebase before any service touches it. Real options are
      // generated by `flutterfire configure` (see lib/firebase_options.dart).
      // If initialization fails (e.g. an unsupported platform such as
      // desktop), the app shows a clear configuration notice instead of
      // crashing.
      bool firebaseConfigured = false;
      Object? firebaseInitError;
      try {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
        firebaseConfigured = true;
      } catch (error) {
        firebaseInitError = error;
      }

      final prefs = await SharedPreferences.getInstance();

      // Services (constructor injection; no service locators or globals).
      final AuthServiceBase authService = AuthService();
      final conversationService = ConversationService();
      final secureStorageService = SecureStorageService();
      final providerConfigService = ProviderConfigService(
        secureStorage: secureStorageService,
      );
      final ChatService chatService = OpenAICompatibleChatService();

      // State providers.
      final themeProvider = ThemeProvider(prefs: prefs);
      await themeProvider.initialize();

      final authProvider = AppAuthProvider(authServiceBase: authService);
      final conversationProvider = ConversationProvider(
        service: conversationService,
      );
      final aiProviderConfigProvider = AIProviderConfigProvider(
        service: providerConfigService,
        chatService: chatService,
      );
      final chatProvider = ChatProvider(
        conversationService: conversationService,
        aiProviderConfigProvider: aiProviderConfigProvider,
        chatService: chatService,
      );

      if (firebaseConfigured) {
        authProvider.start();
      }

      FlutterError.onError = (details) {
        debugPrint('FlutterError: ${details.exception}');
      };
      PlatformDispatcher.instance.onError = (error, stack) {
        debugPrint('Uncaught platform error: $error');
        return true;
      };

      runApp(
        MultiProvider(
          providers: [
            ChangeNotifierProvider.value(value: themeProvider),
            ChangeNotifierProvider.value(value: authProvider),
            ChangeNotifierProvider.value(value: conversationProvider),
            ChangeNotifierProvider.value(value: chatProvider),
            ChangeNotifierProvider.value(value: aiProviderConfigProvider),
          ],
          child: AIWorkspaceApp(
            authProvider: authProvider,
            firebaseConfigured: firebaseConfigured,
            firebaseInitError: firebaseInitError,
          ),
        ),
      );
    },
    (error, stack) {
      debugPrint('Zone error: $error');
    },
  );
}

/// Root widget: custom Material 3 themes + GoRouter navigation + per-user
/// stream wiring on auth changes.
class AIWorkspaceApp extends StatefulWidget {
  const AIWorkspaceApp({
    super.key,
    required this.authProvider,
    required this.firebaseConfigured,
    this.firebaseInitError,
  });

  final AppAuthProvider authProvider;
  final bool firebaseConfigured;
  final Object? firebaseInitError;

  @override
  State<AIWorkspaceApp> createState() => _AIWorkspaceAppState();
}

class _AIWorkspaceAppState extends State<AIWorkspaceApp> {
  late final GoRouter _router;

  @override
  void initState() {
    super.initState();
    _router = buildAppRouter(widget.authProvider);
    widget.authProvider.addListener(_onAuthChanged);
    // Defer the initial wiring past the build phase: calling
    // startListening (which notifies listeners) during build would trigger
    // "markNeedsBuild() called during build".
    WidgetsBinding.instance.addPostFrameCallback((_) => _onAuthChanged());
  }

  /// Starts/stops per-user Firestore stream subscriptions as the signed-in
  /// user changes, and clears all user-scoped state on sign-out. Listener
  /// notifications from the auth provider can arrive mid-build (the router
  /// rebuilds when auth state changes), so the actual provider updates are
  /// always deferred to the next frame.
  void _onAuthChanged() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      final auth = widget.authProvider;
      if (auth.initializing) return;
      if (auth.isSignedIn) {
        final uid = auth.user!.uid;
        context.read<ConversationProvider>().startListening(uid);
        context.read<AIProviderConfigProvider>().startListening(uid);
      } else {
        context.read<ConversationProvider>().clear();
        context.read<ChatProvider>().clearState();
        context.read<AIProviderConfigProvider>().clearState();
      }
    });
  }

  @override
  void dispose() {
    widget.authProvider.removeListener(_onAuthChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'AI Workspace',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: context.watch<ThemeProvider>().themeMode,
      routerConfig: _router,
      builder: (context, child) {
        if (!widget.firebaseConfigured) {
          return FirebaseUnconfiguredNotice(error: widget.firebaseInitError);
        }
        return child ?? const SizedBox.shrink();
      },
    );
  }
}

/// Full-screen notice shown when the app runs without generated Firebase
/// options. Explains the `flutterfire configure` step instead of showing
/// a broken protected screen.
class FirebaseUnconfiguredNotice extends StatelessWidget {
  const FirebaseUnconfiguredNotice({super.key, this.error});

  final Object? error;

  @override
  Widget build(BuildContext context) {
    final theme = ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFFAF9F7),
      colorScheme: ColorScheme.fromSeed(seedColor: Color(0xFF5B5FE9)),
    );
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Theme(
        data: theme,
        child: Material(
          color: theme.scaffoldBackgroundColor,
          child: Center(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(32),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(
                    Icons.cloud_off_outlined,
                    size: 56,
                    color: theme.colorScheme.error,
                  ),
                  const SizedBox(height: 16),
                  Text(
                    'Firebase could not start',
                    style: theme.textTheme.headlineSmall?.copyWith(
                      fontWeight: FontWeight.w600,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 12),
                  ConstrainedBox(
                    constraints: const BoxConstraints(maxWidth: 480),
                    child: Text(
                      error is AppException
                          ? (error as AppException).message
                          : 'Firebase failed to initialize for this '
                                'platform or build configuration.\n\n'
                                'If this platform (e.g. macOS, Windows, or '
                                'Linux desktop) is missing from your Firebase '
                                'registration, re-run:\n\n'
                                'flutterfire configure\n\n'
                                'and select the platform. See README.md → '
                                '"Firebase setup" for details.',
                      textAlign: TextAlign.center,
                      style: theme.textTheme.bodyMedium?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                        height: 1.5,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
